all:
  hosts:
    container1:
      ansible_host: localhost
      ansible_port: 2222
      ansible_user: ansible
      ansible_password: ansible
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    container2:
      ansible_host: localhost
      ansible_port: 2223
      ansible_user: ansible
      ansible_password: ansible
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    container3:
      ansible_host: localhost
      ansible_port: 2224
      ansible_user: ansible
      ansible_password: ansible
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    container4:
      ansible_host: localhost
      ansible_port: 2225
      ansible_user: ansible
      ansible_password: ansible
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'